image:
  file: .gitpod.Dockerfile

# List of VS Code extensions to be installed
vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard

# Commands to run on start
tasks:
  - init: echo 'Initialization commands can go here'
    command: echo 'Startup commands like running your Spring Boot app can go here'
